# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  solutionFile: 'EStore.sln'

steps:
- task: UseDotNet@2
  inputs:
    version: '7.x'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solutionFile)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter DisplayName~UnitTests'
